/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://duwogizonzbyxmamfty7ggbj2e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wjh47desb5cnnecuis6gk32fsu",
    "aws_cognito_identity_pool_id": "us-east-1:67d51de7-0a19-4313-9f5f-9dcefe568373",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GArtCzKkK",
    "aws_user_pools_web_client_id": "4bprrfm6p8ve8ub1p86sgic0v",
    "oauth": {},
    "aws_user_files_s3_bucket": "postagram8d583b4fc11a41068ffd0d61d6058426144058-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
